name: "context" in GitHub Actions

on: 
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
  job1:
    runs-on: self-hosted
    steps:
      - name: "Use GitHub Context"
        run: |
          echo "Hello! This is $MY_ACTION"
          echo "Hello!! This is $MY_ACTOR"
        env:
          MY_ACTION: ${{ github.action }}
          MY_ACTOR: ${{ github.actor }}