name: "two jobs dependency example"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  job2:
    needs: job1
    runs-on: self-hosted
    steps:
      - name: "This is job 2"
        run: echo "Hello! I am job 2"
  job1:
    runs-on: self-hosted
    steps:
      - name: "This is job 1"
        run: echo "Hello! I am job 1"